name: buy_it_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: '0.5.3'
  firebase_auth: '^0.18.4+1'
  cloud_firestore: '^0.14.4'
  provider: ^4.0.5
  shared_preferences: ^0.5.7+3
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/icons/
    - images/jackets/
    - images/trousers/
    - images/shoes/
    - images/t-shirts/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
